name: Deploy front

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
 deploy:
    runs-on: self-hosted
    steps:      
      - name: Pull Docker image from Docker Hub
        run: docker pull pixelapi/angular_app:latest

      - name: Delete old container
        run: sudo docker rm -f angular_app_container

      - name: Run Docker container
        run: docker run -d -p 4200:4200 --name angular_app_container --network api_network pixelapi/angular_app:latest
